# Base configuration
base:
  world_size: 1
  epochs: 0.1
  seed: 0
  unwrap: false
  log_dir: logs/uresnet
  log_step: 1
  overwrite_log: true

# IO configuration
io:
  loader:
    batch_size: 32
    shuffle: false
    num_workers: 4
    collate_fn: all
    dataset:
      name: larcv
      file_list: /global/cfs/cdirs/m5252/dune/sim/protodune-sp/mpvmpr_v0/test_file_list.txt
      schema:
        data:
          parser: sparse3d
          sparse_event: sparse3d_pcluster
        seg_label:
          parser: sparse3d
          sparse_event: sparse3d_pcluster_semantics

# Model configuration
model:
  name: uresnet
  weight_path: weights/uresnet/snapshot*.ckpt

  network_input:
    data: data
  loss_input:
    seg_label: seg_label

  modules:
    uresnet:
      num_input: 1
      num_classes: 5
      filters: 32
      depth: 5
      reps: 2
      allow_bias: false
      activation:
        name: lrelu
        negative_slope: 0.33
      norm_layer:
        name: batch_norm
        eps: 0.0001
        momentum: 0.01

    uresnet_loss:
      balance_loss: false
